# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #mysql数据库连接驱动jar
    username: root  #数据库用户名
    password: root  #数据库密码
    url: jdbc:mysql://localhost:3306/chat?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC  #数据库连接的url
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: HTML # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html #文本类型
#showSql
logging:
  level:
    com:
      chat:
        mapper: debug   #mapper 层 CURD 操作Log
uploadPath: C:/uploadFiles/  #写入硬盘路径
folderName: uploadFiles/    #回显带上文件夹
server:
  port: 8888